export const currentWeather = {
  epochTime: "1658137680",
hasPrecipitation: false,
isDayTime: true,
link: "http://www.accuweather.com/en/il/jerusalem/213225/current-weather/213225?lang=en-us",
localObservationDateTime: "2022-07-18T12:48:00+03:00",
mobileLink: "http://www.accuweather.com/en/il/jerusalem/213225/current-weather/213225?lang=en-us",
precipitationType: null,
temperature: {
  imperial: {value: 86, unit: 'F', unitType: 18},
  metric: {value: 30.2, unit: 'C', unitType: 17}
},
weatherIcon: 1,
weatherText: "Sunny",
}

export const cities1 = [
  {
    administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
    country:{id: "IL", localizedName: "Israel"},
    key: "213225",
    localizedName: "haifa District",
    rank: 285,
    type: "City",
    version: 1,
    },
    {
      administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
      country:{id: "IL", localizedName: "Israel"},
      key: "213225",
      localizedName: "haifa District",
      rank: 285,
      type: "City",
      version: 1,
      },
      {
        administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
        country:{id: "IL", localizedName: "Israel"},
        key: "213225",
        localizedName: "haifa District",
        rank: 285,
        type: "City",
        version: 1,
        },
        {
          administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
          country:{id: "IL", localizedName: "Israel"},
          key: "213225",
          localizedName: "haifa District",
          rank: 285,
          type: "City",
          version: 1,
          },
          {
            administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
            country:{id: "IL", localizedName: "Israel"},
            key: "213225",
            localizedName: "haifa District",
            rank: 285,
            type: "City",
            version: 1,
            },
            {
              administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
              country:{id: "IL", localizedName: "Israel"},
              key: "213225",
              localizedName: "haifa District",
              rank: 285,
              type: "City",
              version: 1,
              },
              {
                administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                country:{id: "IL", localizedName: "Israel"},
                key: "213225",
                localizedName: "haifa District",
                rank: 285,
                type: "City",
                version: 1,
                },
                {
                  administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                  country:{id: "IL", localizedName: "Israel"},
                  key: "213225",
                  localizedName: "haifa District",
                  rank: 285,
                  type: "City",
                  version: 1,
                  },
                  {
                    administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                    country:{id: "IL", localizedName: "Israel"},
                    key: "213225",
                    localizedName: "haifa District",
                    rank: 285,
                    type: "City",
                    version: 1,
                    },
                    {
                      administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                      country:{id: "IL", localizedName: "Israel"},
                      key: "213225",
                      localizedName: "haifa District",
                      rank: 285,
                      type: "City",
                      version: 1,
                      },
                      {
                        administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                        country:{id: "IL", localizedName: "Israel"},
                        key: "213225",
                        localizedName: "haifa District",
                        rank: 285,
                        type: "City",
                        version: 1,
                        },
                        {
                          administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                          country:{id: "IL", localizedName: "Israel"},
                          key: "213225",
                          localizedName: "haifa District",
                          rank: 285,
                          type: "City",
                          version: 1,
                          },
                          {
                            administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                            country:{id: "IL", localizedName: "Israel"},
                            key: "213225",
                            localizedName: "haifa District",
                            rank: 285,
                            type: "City",
                            version: 1,
                            },
                            {
                              administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                              country:{id: "IL", localizedName: "Israel"},
                              key: "213225",
                              localizedName: "haifa District",
                              rank: 285,
                              type: "City",
                              version: 1,
                              },
                              {
                                administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                                country:{id: "IL", localizedName: "Israel"},
                                key: "213225",
                                localizedName: "haifa District",
                                rank: 285,
                                type: "City",
                                version: 1,
                                },
                                {
                                  administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                                  country:{id: "IL", localizedName: "Israel"},
                                  key: "213225",
                                  localizedName: "haifa District",
                                  rank: 285,
                                  type: "City",
                                  version: 1,
                                  },
                                  {
                                    administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                                    country:{id: "IL", localizedName: "Israel"},
                                    key: "213225",
                                    localizedName: "haifa District",
                                    rank: 285,
                                    type: "City",
                                    version: 1,
                                    },
                                    {
                                      administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                                      country:{id: "IL", localizedName: "Israel"},
                                      key: "213225",
                                      localizedName: "haifa District",
                                      rank: 285,
                                      type: "City",
                                      version: 1,
                                      },
                                      {
                                        administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
                                        country:{id: "IL", localizedName: "Israel"},
                                        key: "213225",
                                        localizedName: "haifa District",
                                        rank: 285,
                                        type: "City",
                                        version: 1,
                                        },
    {
      administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
      country:{id: "IL", localizedName: "America"},
      key: "213225",
      localizedName: "haifa 235",
      rank: 285,
      type: "City",
      version: 1,
      }
  ];

  export const cities2 = [
    {
    administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
    country:{id: "IL", localizedName: "America"},
    key: "213225",
    localizedName: "Jerusalem District",
    rank: 285,
    type: "City",
    version: 1,
    },
    {
      administrativeArea: {ID: Array(0), LocalizedName: Array(0)},
      country:{id: "IL", localizedName: "Israel"},
      key: "213225",
      localizedName: "Jerusalem 235",
      rank: 285,
      type: "City",
      version: 1,
      }
  ];